### ISSUE TITLE
Terminal app bugged when resizing and dragging.

### ISSUE THREAD

**Issue by iDCoded** [mhmdmhd6/Mac-OS-Desktop#15]
I was just testing the **Terminal** app.

I made it fullscreen and then minimized it, and after that when I was dragging the window with my mouse, this happened. 

⬇️ 

![Buggged Terminal](https://user-images.githubusercontent.com/65074550/142131059-e69d8eb8-d5e9-48f5-aa04-94bc57b971ac.png)

**Comment by goxr3plus** [comment]
Dammnn we need to fix it :)

**Comment by iDCoded** [comment]
> Dammnn we need to fix it :)

Yes, but I think this has been fixed already.
➡️ #17 ⬅️
