### ISSUE TITLE
Contribute in this project

### ISSUE THREAD

**Issue by arminamirinasab** [mhmdmhd6/Mac-OS-Desktop#28]
Hello, I checked this code and I was really surprised that it works very smoothly and perfectly. I found some bugs in this project and I am really interested in contributing to this project. I wanted to ask your opinion before sending the pull request :)

**Comment by mhmdmhd6** [comment]
Hello, thank you, I will be happy if you improve this project. feel free to send a pull request.

**Comment by arminamirinasab** [comment]
thank you 🙏👋
