### ISSUE TITLE
Bug: Display charge status in mobile 

### ISSUE THREAD

**Issue by nafasebra** [mhmdmhd6/Mac-OS-Desktop#30]
Hi,
I was visiting the project, but i see this issue about display charge status.

![IMG_20230121_190940.jpg](https://user-images.githubusercontent.com/74317517/213874520-0897399e-8262-4f4c-bf2f-12be22fec3a3.jpg)

**Comment by arminamirinasab** [comment]
Hi Dear Nafas 👋

I think this problem is due to not rounding the numbers when receiving the battery information, I will work on the method as soon as possible.
@nafasebra

**Comment by arminamirinasab** [comment]
I solved this problem & sent the PR

**Comment by mhmdmhd6** [comment]
Thank you sir!
