### ISSUE TITLE
FUNDING

### ISSUE THREAD

**Issue by BlackIQ** [mhmdmhd6/Mac-OS-Desktop#7]
Hi,

If you are looking for sponsors first go to [Sponsor page](github.com/sponsors) and register for verification. After verification create a repository with **.github** name. Add a README.md and a FUNDING.yml file in it.
in yml file put these lines:
```yml
github: mhmdmhd6
tidelift: mhmdmhd6/Mac-OS-Desktop
```

You can remove FUNDING.yml from this repo when you make .github repository.
If there is any question you can send me Emails or ask them in Telegram.

[Email](me@blackiq.ir)
[Telegram](https://t.me/BlackIQ)

Goodnight.
May the force be with you.
Bye.

**Close this when you read**

**Comment by mhmdmhd6** [comment]
Hi,
Thanks for your guide @BlackIQ 🙏,
but Iran is one the unsupported countries on github sponsers part.
> Hi,
> 
> If you are looking for sponsors first go to [Sponsor page](github.com/sponsors) and register for verification. After verification create a repository with **.github** name. Add a README.md and a FUNDING.yml file in it.
> in yml file put these lines:
> 
> ```yaml
> github: mhmdmhd6
> tidelift: mhmdmhd6/Mac-OS-Desktop
> ```
> 
> You can remove FUNDING.yml from this repo when you make .github repository.
> If there is any question you can send me Emails or ask them in Telegram.
> 
> [Email](me@blackiq.ir)
> [Telegram](https://t.me/BlackIQ)
> 
> Goodnight.
> May the force be with you.
> Bye.
> 
> **Close this when you read**

**Comment by BlackIQ** [comment]
I know, I live in Iran too. but you have a great repository.
Have fun.

Amir.

**Comment by mhmdmhd6** [comment]
Thanks🙏❤
you too, good luck.
> I know, I live in Iran too. but you have a great repository.
> Have fun.
> 
> Amir.
